services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    ports:
      - "8090:80"
    volumes:
      - ../../projetos/serie:/var/www/html/serie
      - ../../projetos/administracao:/var/www/html/administracao
      - ../../projetos/suporte:/var/www/html/suporte
      - ../../projetos/beachbauru:/var/www/html/beachbauru
      - ../../projetos/junior:/var/www/html/junior
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php_errors.log:/var/log/
      - ./tmp:/var/www/html/tmp
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      # Timezone
      TZ: "America/Sao_Paulo"
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y git unzip curl libpng-dev libjpeg62-turbo-dev libfreetype6-dev libonig-dev libzip-dev nodejs npm && 
      docker-php-ext-install pdo_mysql mysqli calendar mbstring zip gd bcmath && 
      apache2-foreground
      "

  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minha_base
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql  

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /app
    volumes:
      - ./app:/app

  node:
    image: node:20
    container_name: node
    working_dir: /app
    volumes:
      - ./app:/app
    command: bash
    
volumes:
  mysql_data: