services:
  php:
    build: .
    image: shinsenter/php:5.6-apache
    volumes:
      - ../../projetos/administracao:/var/www/html/administracao
      - ../../projetos/suporte:/var/www/html/suporte
      - ../../projetos/beachbauru:/var/www/html/beachbauru
      - ../../projetos/junior:/var/www/html/junior
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php_errors.log:/var/log/
      - ./tmp:/var/www/html/tmp
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minha_base
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin56
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data: